### ISSUE TITLE
Add support for a 'server key'

### ISSUE THREAD

**Issue by shakvaal** [zaf/asterisk-googletts#10]
e.g. `agi(googletts.agi,"text",[language],[intkey],[speed],[serverkey])`

The `serverkey`, when provided, is then passed into all API requests as a `key=<serverkey>` parameter, according to official [Google guide](https://developers.google.com/console/help/new/#generatingdevkeys).

Same goes for [zaf/asterisk-googletranslate](https://github.com/zaf/asterisk-googletranslate).

**Comment by FabMira** [comment]
hey i've joined the group but I've haven't found the way to get de API key, could you be mor specific?
