### ISSUE TITLE
execute from command line

### ISSUE THREAD

**Issue by johnpaulmedina** [zaf/asterisk-googletts#16]
How can execute the AGIA from the originate applicate ?

originate SIP/13053053005@outbound-trunk application agi googletts.agi,"Testing google agi",en,any

**Comment by sesardelaisla** [comment]
Sorry to ask in such an old and closed issue, but I am trying to replicate this and behavior is not as expected. If I type the following, I hear the first word only and with English accent.

`originate Local/686xxxxxx@external-calls application agi googletts.agi,"Esto es una prueba de traducción de Google.",es,any`

Can you advise on how the script can say the whole sentence in Spanish, please?
