### ISSUE TITLE
Google is now redirecting to a CAPTCHA page

### ISSUE THREAD

**Issue by pla1** [zaf/asterisk-googletts#17]
Hi, 

Thanks for a great tool. Unfortunately Google is now redirecting to a CAPTCHA page. Let us know if you find a work-around. 

Thanks, PLA

**Comment by zaf** [comment]
Thank you for the notice, I have just pushed an updated version that seems to work here. Please test and report.

**Comment by yusufgungor** [comment]
Can you add error notify about captcha issues? Because even captcha error the script was return 0. By the way thanks you very much for quick fix.

**Comment by pla1** [comment]
New version of googletts.agi is not working for me so I tried the following command. 

htplainf@ub-asterisk:~$ perl  ./googletts-cli.pl -t "This is a test" -o test.wav
Failed to fetch speech data. at ./googletts-cli.pl line 135.

Is my syntax correct?

**Comment by zaf** [comment]
Hello,
syntax seems correct. Can't reproduce the issue here, both script are working, have you pulled the latest version?

**Comment by pla1** [comment]
I have the latest version. Any troubleshooting suggestions? 

![tts](https://cloud.githubusercontent.com/assets/426549/8956974/e754a8a4-35c8-11e5-9fd4-0cb6c03ddc2a.png)

**Comment by pla1** [comment]
I tried it on another machine and it works. Something different about my Asterisk server. I will troubleshoot some more. Sorry for the bother. Thanks, PLA

**Comment by zaf** [comment]
Could be google blocking your IP after it detected a lot of requests. I have seen it happening a few times.

**Comment by pla1** [comment]
This is bizarre. I put a print statement in googletts-cli.pl to get the URL. The URL works fine in a browser on another machine, works fine with wget on another machine, wget fails from my Asterisk server. Both machines are behind the same Cisco firewall and use the same NAT'ed public IP address. Why in the world is Google responding differently between the two requests? :8ball: 

![tts](https://cloud.githubusercontent.com/assets/426549/8957789/cd46f038-35ce-11e5-8fcc-1a4d4485f151.png)

**Comment by pla1** [comment]
Please consider adding `use LWP::Protocol::https;` to the Perl scripts so that the user is notified of the missing module instead of silently failing. 

The `LWP::Protocol::https;` module was missing on a couple of Ubuntu systems. I installed the missing module with cpan. On one system I additionally had to `sudo apt-get install liblwp-protocol-https-perl` prior to installing the missing module in cpan. 

All systems are working now. 

Thanks, PLA
