### ISSUE TITLE
Not working with Centos 7.1 & Asterisk 11

### ISSUE THREAD

**Issue by mark847** [zaf/asterisk-googletts#20]
I have 64 bit Centos 7.1.1503, Asterisk 11.19.0 with Incredible GUI 2.11.0.34.
I updated googletts.agi with the 7/29/15 code, but I do not get any sound even though the built-in gsm files playback.  I have sox, and mpg123 installed. Further
yum install...
Package 4:perl-5.16.3-285.el7.x86_64 already installed and latest version
Package perl-Crypt-SSLeay-0.64-5.el7.x86_64 already installed and latest version
No package perl-libwww available.

I have internet connection running. I ran asterisk -vvvvvvvvvvvvvvvvr and I can see the string being called with asterisk.agi:
 AGI("SIP/701-00000004", "googletts.agi,"This Top Stories news update brought to you by Yahoo and Nerd Viddles.  From Yahoo Finance: Wall Street tumbles in volatile action amid global rout. From Reuters: How a New Orleans church found salvation from Katrina in Texas. From Reuters: How President Bernie Sanders would handle foreign policy. From Reuters: New Orleans' finances still vulnerable 10 years after Katrina: Moody's. From Reuters: Judge to decide whether Pennsylvania official will face perjury trial. From Reuters: Researchers sample enormous oceanic trash vortex ahead of clean-up proposal. From Associated Press: Americans  Briton who thwarted attack get France's top honor. From Associated Press: IndyCar driver Justin Wilson in coma after wreck at Pocono. From Associated Press: How Trump would pull off his immigration plan. Have a nice day. Goodbye.",en") in new stack
    -- Launched AGI Script /var/lib/asterisk/agi-bin/googletts.agi
    -- <SIP/701-00000004>AGI Script googletts.agi completed, returning 0
    -- Executing [951@from-internal:8] Hangup("SIP/701-00000004", "") in new stack
  == Spawn extension (from-internal, 951, 8) exited non-zero on 'SIP/701-00000004'
    -- Executing [h@from-internal:1] Hangup("SIP/701-00000004", "") in new stack
  == Spawn extension (from-internal, h, 1) exited non-zero on 'SIP/701-00000004'
The Hangup string happens almost immediately.

QUESTIONS:
How do I check to see if I have the perl-libwww installed?  
How can I debug googletts.agi from the linux command line?  
Where can I find the temporary wav file?
My asterisk defaults to gsm, will it also work with wav?

**Comment by zaf** [comment]
Hello,

the packages for Centos7 should be:
perl-libwww-perl and perl-LWP-Protocol-https
give them a try. To debug the script first you can try running it by hand to see if it loads properly and no perl plugins are missing, this is a first step to make sure you perl environment is sane.
To debug it in asterisk enable debug output in the script by setting $debug = 1; in the ' User defined parameters' section and then make sure to start asterisk manually by 'asterisk -cvvv' so you can actually see the AGI debug output in your console.

**Comment by mark847** [comment]
Thank you.  The perl library was installed, but the  yum install  perl-LWP-Protocol-https was not installed.
That fixed the problem!
PS.  I still don't know the syntax for running it by hand from the Linux command line.  Any help there would be greatly appreciated. Thanks.

**Comment by zaf** [comment]
Hello,

you can run it like any other perl script:

perl /path/to/googletts.agi

if these is some perl module missing it will throw an error and exit. If all is good it will start and wait for input. It is supposed to get the AGI environment args to start the AGI session. In this case you can terminate it by pressing Ctrl-C and proceed to test it in asterisk.
