### ISSUE TITLE
not working on freepbx

### ISSUE THREAD

**Issue by chicco83** [zaf/asterisk-googletts#23]
hi i had googletts working for two years.
my setup is freepbx version 12.0.76.1 with asterisk Ver. 11.16.0
now, even with the updated script it gives me errors.
this is the output if i use googletts.agi

>[root@localhost agi-bin]# perl googletts.agi -o hello.wav -l it -t "Hello world"
>Use of uninitialized value $AGI{"request"} in concatenation (.) or string at googletts.agi line 95, <STDIN> line 1.
> -- : Invalid language setting. Using default.
>CHANNEL STATUS
 >-- : Unexpected result:
>GET FULL VARIABLE ${CHANNEL(audionativeformat)}
 >-- : Unexpected result:
 >-- : Failed to fetch file.

this one is the one using the googletts-cli.pl which is the file i used before

>[root@localhost agi-bin]# ./googletts-cli.pl -o hello.wav -l en -t "Hello world"
>Failed to fetch speech data. at ./googletts-cli.pl line 126.

i can manually download the tts file with this command
wget -q -U Mozilla -O output.mp3 "http://translate.google.com/translate_tts?ie=UTF-8&client=t&tl=it&q= hello world"

**Comment by jadermorais** [comment]
hello, I'm same problem.

**Comment by zaf** [comment]
Google started detecting and blocking 3rd party access on their TTS API on the translate page.
They seem determined to stop people from getting speech data.
I'm looking for a way around but I can't promise anything yet.

**Comment by zaf** [comment]
A possible fix is pushed: https://github.com/zaf/asterisk-googletts/commit/0d790d7644ae9750a869bfc47f845391defa133b

**Comment by marco1957** [comment]
Hi
Yesterday I discovered in my asterisk that  googletts.agi not worked as on august 2015. So I downloaded and installed the last version of googletts.agi, but I have the same problem:
-- Launched AGI Script /var/lib/asterisk/agi-bin/googletts.agi
-- <SIP/6020-0000000a>AGI Script googletts.agi completed, returning 0
What can I try to solve it?
Thanks
Marco

**Comment by jadermorais** [comment]
no work, is limited for Google 
Não está funcionando estou em busca de outros projetos "tts free", eu li que o googletts não está funcionando por conta de uma limitação do Google.

Jader Morais 



Date: Tue, 19 Jan 2016 00:34:43 -0800

**Comment by zaf** [comment]
The script is working for now, see [here](https://github.com/zaf/asterisk-googletts/issues/24#issuecomment-167460958). Please try some up to date code.
