### ISSUE TITLE
Error: googletts.agi: Failed to fetch file.

### ISSUE THREAD

**Issue by fesalata** [zaf/asterisk-googletts#26]
**Log in Asterisk:**
-- <SIP/1000-00000003>AGI Script googletts.agi completed, returning 0
    -- Executing [9999@atendimento:19] AGI("SIP/1000-00000003", "googletts.agi,"Para ouvir novamente. Digite 9",pt-BR,any") in new stack
    -- Launched AGI Script /var/lib/asterisk/agi-bin/googletts.agi
<SIP/1000-00000003>AGI Tx >> agi_request: googletts.agi
<SIP/1000-00000003>AGI Tx >> agi_channel: SIP/1000-00000003
<SIP/1000-00000003>AGI Tx >> agi_language: pt_BR
<SIP/1000-00000003>AGI Tx >> agi_type: SIP
<SIP/1000-00000003>AGI Tx >> agi_uniqueid: 1448549400.3
<SIP/1000-00000003>AGI Tx >> agi_version: 1.8.25.0
<SIP/1000-00000003>AGI Tx >> agi_callerid: 1000
<SIP/1000-00000003>AGI Tx >> agi_calleridname: Atendimento
<SIP/1000-00000003>AGI Tx >> agi_callingpres: 0
<SIP/1000-00000003>AGI Tx >> agi_callingani2: 0
<SIP/1000-00000003>AGI Tx >> agi_callington: 0
<SIP/1000-00000003>AGI Tx >> agi_callingtns: 0
<SIP/1000-00000003>AGI Tx >> agi_dnid: 9999
<SIP/1000-00000003>AGI Tx >> agi_rdnis: unknown
<SIP/1000-00000003>AGI Tx >> agi_context: atendimento
<SIP/1000-00000003>AGI Tx >> agi_extension: 9999
<SIP/1000-00000003>AGI Tx >> agi_priority: 19
<SIP/1000-00000003>AGI Tx >> agi_enhanced: 0.0
<SIP/1000-00000003>AGI Tx >> agi_accountcode: 5
<SIP/1000-00000003>AGI Tx >> agi_threadid: -1254835344
<SIP/1000-00000003>AGI Tx >> agi_arg_1: Para ouvir novamente. Digite 9
<SIP/1000-00000003>AGI Tx >> agi_arg_2: pt-BR
<SIP/1000-00000003>AGI Tx >> agi_arg_3: any
<SIP/1000-00000003>AGI Tx >> 
Use of uninitialized value $AGI{"arg_4"} in length at /var/lib/asterisk/agi-bin/googletts.agi line 130, <STDIN> line 24.
<SIP/1000-00000003>AGI Rx << CHANNEL STATUS
<SIP/1000-00000003>AGI Tx >> 200 result=6
 -- googletts.agi: Command returned: 200 result=6
<SIP/1000-00000003>AGI Rx << GET FULL VARIABLE ${CHANNEL(audionativeformat)}
<SIP/1000-00000003>AGI Tx >> 200 result=1 (ulaw)
 -- googletts.agi: Command returned: 200 result=1 (ulaw)
 -- googletts.agi: Text passed for synthesis: Para ouvir novamente. Digite 9.
 -- googletts.agi: Language: pt-BR, Interrupt keys: 0123456789#*, Sample rate: 8000
 -- googletts.agi: Speed: 1.3, Caching: 1, Cache dir: /googletts_audio
 -- googletts.agi: URL passed: https://translate.google.com/translate_tts?ie=UTF-8&q=Para%20ouvir%20novamente.%20Digite%209.&tl=pt-BR&total=1&idx=0&textlen=31&client=t&tk=87295|20611
 -- googletts.agi: Failed to fetch file.
 -- googletts.agi: Cleaning temp files.

______________________XXXXX___________________________

**Result on command line:**
root@sneppbx:~/asterisk-googletts# perl googletts.agi "test"  "en"

Use of uninitialized value $AGI{"request"} in concatenation (.) or string at googletts.agi line 96, <STDIN> line 1.
Use of uninitialized value $AGI{"arg_3"} in length at googletts.agi line 125, <STDIN> line 1.
Use of uninitialized value $AGI{"arg_4"} in length at googletts.agi line 130, <STDIN> line 1.
CHANNEL STATUS

 -- : Unexpected result: 
GET FULL VARIABLE ${CHANNEL(audionativeformat)}

 -- : Unexpected result: 
 -- : Failed to fetch file.

______________________XXXXX___________________________
**Using the command:**
*perl ./googletts-cli.pl -t "testing googletts" -o testing.wav*
The audio file is properly synthesized.

______________________XXXXX___________________________
System:
**Debian Wheezy**
**Asterisk 1.8.25.0**
**installed: git sox mpg123 libwww-perl perl libcrypt-ssleay-perl libsox-fmt-mp3 liblwp-protocol-https-perl**

**Comment by zaf** [comment]
Thank you for the very detailed report. There was actually an error in googletts.agi in the HTTP request creation. This is now fixed, please get the latest trunk code and test.

**Comment by fesalata** [comment]
I thank you for your great work and commitment to solve everything so quickly

Works fine now.. thanks...
