### ISSUE TITLE
Unexpected result using googletts

### ISSUE THREAD

**Issue by mobilyws** [zaf/asterisk-googletts#28]
Hello zaf , 
Thanks for your effort here , 

can you assist me to found solution for my issue ? 

==================
perl /var/lib/asterisk/agi-bin/googletts.agi -l de -t "HalloHallo" -o test.wav

Use of uninitialized value $AGI{"request"} in concatenation (.) or string at /var/lib/asterisk/agi-bin/googletts.agi line 96, <STDIN> line 1.
CHANNEL STATUS

 -- : Unexpected result:
GET FULL VARIABLE ${CHANNEL(audionativeformat)}

 -- : Unexpected result:

STREAM FILE /tmp/ggl_dSfXLX1G ""
 -- : Unexpected result:
 -- : Failed to play /tmp/ggl_dSfXLX1G.
NOOP " -- : Failed to play /tmp/ggl_dSfXLX1G."
 -- : Unexpected result:
Died at /var/lib/asterisk/agi-bin/googletts.agi line 233, <STDIN> line 5.

**Comment by zaf** [comment]
Hello,

you are trying to use the AGI script instead of the cli app. The AGI script is supposed to be called from asterisk, not manually via the command line interface. You actually want to use the script 'googletts-cli.pl' found in the folder 'cli' in the source tree.

**Comment by mobilyws** [comment]
Thanks for instant replay ..
