### ISSUE TITLE
Not working now(

### ISSUE THREAD

**Issue by Plushkin** [zaf/asterisk-googletts#31]
-- Executing [1234@from-internal:2] AGI("SIP/126-00000319", "googletts.agi,"This is a simple google text to speech test in english.",en") in new stack
    -- Launched AGI Script /var/lib/asterisk/agi-bin/googletts.agi
<SIP/126-00000319>AGI Tx >> agi_request: googletts.agi
<SIP/126-00000319>AGI Tx >> agi_channel: SIP/126-00000319
<SIP/126-00000319>AGI Tx >> agi_language: ru
<SIP/126-00000319>AGI Tx >> agi_type: SIP
<SIP/126-00000319>AGI Tx >> agi_uniqueid: 1477571818.1201
<SIP/126-00000319>AGI Tx >> agi_version: 11.21.2
<SIP/126-00000319>AGI Tx >> agi_callerid: 126
<SIP/126-00000319>AGI Tx >> agi_calleridname: unknown
<SIP/126-00000319>AGI Tx >> agi_callingpres: 1
<SIP/126-00000319>AGI Tx >> agi_callingani2: 0
<SIP/126-00000319>AGI Tx >> agi_callington: 0
<SIP/126-00000319>AGI Tx >> agi_callingtns: 0
<SIP/126-00000319>AGI Tx >> agi_dnid: 1234
<SIP/126-00000319>AGI Tx >> agi_rdnis: unknown
<SIP/126-00000319>AGI Tx >> agi_context: from-internal
<SIP/126-00000319>AGI Tx >> agi_extension: 1234
<SIP/126-00000319>AGI Tx >> agi_priority: 2
<SIP/126-00000319>AGI Tx >> agi_enhanced: 0.0
<SIP/126-00000319>AGI Tx >> agi_accountcode:
<SIP/126-00000319>AGI Tx >> agi_threadid: 140020954314496
<SIP/126-00000319>AGI Tx >> agi_arg_1: This is a simple google text to speech test in english.
<SIP/126-00000319>AGI Tx >> agi_arg_2: en
<SIP/126-00000319>AGI Tx >>
<SIP/126-00000319>AGI Rx << CHANNEL STATUS
<SIP/126-00000319>AGI Tx >> 200 result=6
<SIP/126-00000319>AGI Rx << GET FULL VARIABLE ${CHANNEL(audionativeformat)}
<SIP/126-00000319>AGI Tx >> 200 result=1 ((alaw))
<SIP/126-00000319>AGI Rx << NOOP " -- googletts.agi: Failed to fetch file: "
<SIP/126-00000319>AGI Tx >> 200 result=0
<SIP/126-00000319>AGI Rx << NOOP " -- googletts.agi: 500"
<SIP/126-00000319>AGI Tx >> 200 result=0
<SIP/126-00000319>AGI Rx << NOOP " -- googletts.agi: Can't connect to translate.google.com:443 (connect: Connection refused)"
<SIP/126-00000319>AGI Tx >> 200 result=0
    -- <SIP/126-00000319>AGI Script googletts.agi completed, returning 0

**Comment by zaf** [comment]
The actual error is:

"googletts.agi: Can't connect to translate.google.com:443 (connect: Connection refused)"

Make sure you can reach the remote server in order to get the speech data.
