### ISSUE TITLE
 symbol lookup error: undefined symbol: Perl_Istack_sp_ptr

### ISSUE THREAD

**Issue by Tugzrida** [zaf/asterisk-googletts#37]
Sorry if this is a really dumb question but I've never used perl before and have next to no idea what I'm doing 🙃 

When running `googletts-cli.pl` from the command line on a FreePBX installation, I receive the below error:

```
$ /usr/local/sbin/googletts-cli.pl -l en -f speech.txt -r 8000 -o speech.wav

perl: symbol lookup error: /usr/local/lib64/perl5/auto/Compress/Raw/Zlib/Zlib.so: undefined symbol: Perl_Istack_sp_ptr
```
It was working just a few weeks ago before I updated FreePBX and trying to search for an answer yields a very small number of results on Google, which as far as I can tell only lead to more problems similar to the error message above.

Thanks if you have the time to help me out 😊

**Comment by zaf** [comment]
This looks like a problem with the Perl version of FreePBX, I suspect that something broke after the upgrade. Some packages were upgraded, some Perl modules installed (of left back) compiled with different versions of Perl or something similar with zlib. 
In case you had manually installed some Perl modules via CPAN try reinstalling them.
I'm afraid I can't help you much more with this, if the problem persists maybe fill a bug with FreePBX.
