### ISSUE TITLE
use read cmd instead of playback

### ISSUE THREAD

**Issue by jeffvfren** [zaf/asterisk-googletts#38]
I would like to allow user dialing number during google tts playing.
Is there any way to make it work like asterisk read command?

**Comment by burakvural93** [comment]
I am also wondering this issue,because while file is streaming,user should be able to pass this streaming by dialing something,it can be done thanks to get_data rather than stream_file

**Comment by zaf** [comment]
By setting the interrupt key to 'any' the user can interrupt the streaming. The value of the digit is then used as the extension to jump to, something very common in IVR menus. Please check the sub 'playback' in the AGI script and the examples.
