### ISSUE TITLE
googletts.agi not responding, returning 0

### ISSUE THREAD

**Issue by sorenrosenberg** [zaf/asterisk-googletts#41]
Has google stopped answering our calls? 

I just moved and as such I've had my asterisk server disconnected for a few weeks. I've got a few extensions using the googletts.agi script and they were working fine before moving. However today when I tried connecting everything up, I don't get any response when I call the extensions using the script.

In the debug log of asterisk I can see the script is run as per usual, I get a 

   -- Launched AGI Script /var/lib/asterisk/agi-bin/googletts.agi

And then nothing happens. Eventually it will timeout after a minute or two, returning 0

    -- <SIP/phone_srn-00000001>AGI Script googletts.agi completed, returning 0

**Comment by jeetzz** [comment]
For a strange reason my AGI script were changed, wonder how?

Anyway its sorted now.
