### ISSUE TITLE
asterisk-googletts on centos no sound

### ISSUE THREAD

**Issue by andreafranchi** [zaf/asterisk-googletts#9]
On a fresh centos with astersiknow 11 I try to use asterisk-googletts on a simple extension:

exten => 995,1,Answer
exten => 995,2,agi(googletts.agi,"Il motore di sintetizzazione della voce",it)
exten => 995,3,agi(googletts.agi,"è stato installato",it)
exten => 995,4,agi(googletts.agi,"Arrivederci e grazie.",it)
exten => 995,5,HangUp

The console output is:
Connected to Asterisk 11.2.1 currently running on localhost (pid = 4148)
  == Using SIP RTP TOS bits 184
  == Using SIP RTP CoS mark 5
    -- Executing [995@from-internal:1] Answer("SIP/101-00000000", "") in new stack
    -- Executing [995@from-internal:2] AGI("SIP/101-00000000", "googletts.agi,"Il motore di sintetizzazione della voce",it") in new stack
    -- Launched AGI Script /var/lib/asterisk/agi-bin/googletts.agi
    -- <SIP/101-00000000>AGI Script googletts.agi completed, returning 0
    -- Executing [995@from-internal:3] AGI("SIP/101-00000000", "googletts.agi,"è stato installato",it") in new stack
    -- Launched AGI Script /var/lib/asterisk/agi-bin/googletts.agi
    -- <SIP/101-00000000>AGI Script googletts.agi completed, returning 0
    -- Executing [995@from-internal:4] AGI("SIP/101-00000000", "googletts.agi,"Arrivederci e grazie.",it") in new stack
    -- Launched AGI Script /var/lib/asterisk/agi-bin/googletts.agi
    -- <SIP/101-00000000>AGI Script googletts.agi completed, returning 0
    -- Executing [995@from-internal:5] Hangup("SIP/101-00000000", "") in new stack
  == Spawn extension (from-internal, 995, 5) exited non-zero on 'SIP/101-00000000'
    -- Executing [h@from-internal:1] Hangup("SIP/101-00000000", "") in new stack
  == Spawn extension (from-internal, h, 1) exited non-zero on 'SIP/101-00000000'
localhost*CLI> 

googletts.agi return state 0 that indicate success, but no sound is produced on the phone.

Where I'm wrong?
I have similar issue using speech-recog.agi

Thanks in advance

**Comment by abesherman** [comment]
in centos 6 i did 
sudo yum install perl-libwww-perl
sudo yum install perl-DBI
sudo yum install perl-DBD-MySQL
sudo yum install perl-GD
sudo yum install perl-CGI
sudo yum sox
sudo yum sox-devel

for the mpg123
Create a file repository config file /etc/yum.repos.d/linuxtech.repo

nano /etc/yum.repos.d/linuxtech.repo
# Past this ---------------------------------------------------------------------
    [linuxtech]
    name=LinuxTECH
    baseurl=http://pkgrepo.linuxtech.net/el6/release/
    enabled=1
    gpgcheck=1
    gpgkey=http://pkgrepo.linuxtech.net/el6/release/RPM-GPG-KEY-LinuxTECH.NET
# -------------------------------------------------------------------------------
 yum install mpg123

https://www.digitalocean.com/community/questions/how-to-install-perl-lwp-module-on-centos-7
https://centos.pkgs.org/6/linuxtech/mpg123-1.14.4-1.el6.i686.rpm.html

**Comment by fabiosangiorgi** [comment]
I solved it with

`yum install perl-IO-Socket-SSL.noarch`

and add

`use IO::Socket::SSL;`

in "/var/lib/asterisk/agi-bin/googletts.agi" file

**Comment by janduy** [comment]
Hello .. Good evening,

@fabiosangiorgi

I have a problem with this. I have a problem with the problem. I have a problem with this problem. I have a problem with the problem. does not work. Do you have any tips?

**I will attach below the log of my AGI.**

**LOG:**
 <SIP/8004-00000002>AGI Script googletts.agi completed, returning 0
    -- Executing [s@ivrtime:3] Wait("SIP/8004-00000002", "1") in new stack
    -- Executing [s@ivrtime:4] AGI("SIP/8004-00000002", "googletts.agi,"Digite o seu numero de cliente assim eu posso lhe identificar",pt-BR") in new stack
    -- Launched AGI Script /var/lib/asterisk/agi-bin/googletts.agi
<SIP/8004-00000002>AGI Tx >> agi_request: googletts.agi
<SIP/8004-00000002>AGI Tx >> agi_channel: SIP/8004-00000002
<SIP/8004-00000002>AGI Tx >> agi_language: br
<SIP/8004-00000002>AGI Tx >> agi_type: SIP
<SIP/8004-00000002>AGI Tx >> agi_uniqueid: 1515891322.2
<SIP/8004-00000002>AGI Tx >> agi_version: certified/13.13-cert9
<SIP/8004-00000002>AGI Tx >> agi_callerid: 8004
<SIP/8004-00000002>AGI Tx >> agi_calleridname: 8004
<SIP/8004-00000002>AGI Tx >> agi_callingpres: 0
<SIP/8004-00000002>AGI Tx >> agi_callingani2: 0
<SIP/8004-00000002>AGI Tx >> agi_callington: 0
<SIP/8004-00000002>AGI Tx >> agi_callingtns: 0
<SIP/8004-00000002>AGI Tx >> agi_dnid: 8001
<SIP/8004-00000002>AGI Tx >> agi_rdnis: unknown
<SIP/8004-00000002>AGI Tx >> agi_context: ivrtime
<SIP/8004-00000002>AGI Tx >> agi_extension: s
<SIP/8004-00000002>AGI Tx >> agi_priority: 4
<SIP/8004-00000002>AGI Tx >> agi_enhanced: 0.0
<SIP/8004-00000002>AGI Tx >> agi_accountcode:
<SIP/8004-00000002>AGI Tx >> agi_threadid: 140332354098944
<SIP/8004-00000002>AGI Tx >> agi_arg_1: Digite o seu numero de cliente assim eu posso lhe identificar
<SIP/8004-00000002>AGI Tx >> agi_arg_2: pt-BR
<SIP/8004-00000002>AGI Tx >>
    -- <SIP/8004-00000002>AGI Script googletts.agi completed, returning 0
    -- Executing [s@ivrtime:5] NoOp("SIP/8004-00000002", "..::: ENCERRANDO CHAMADA - IVRTIME ::...") in new stack
    -- Executing [s@ivrtime:6] Hangup("SIP/8004-00000002", "") in new stack

Thank you.

**Comment by janduy** [comment]
Good Morning.

I did another test, I disabled in the code line of "googletts.agi" where check the mpg123 and sox both are already installed.

Commented line:
Abort if required programs not found.
fatal_log ("sox or mpg123 is missing. Aborting.") if (! $ sox || $ mpg123);
chomp ($ sox, $ mpg123);

Follow the new error log, I notice that it generates the link with the message, but it does not start in linux, I validated the link, it works.

I'm using CentOS7.

I will send the log after commenting the line, as I mentioned above.

Launched AGI Script /var/lib/asterisk/agi-bin/googletts.agi
<SIP/8004-0000000b>AGI Tx >> agi_request: googletts.agi
<SIP/8004-0000000b>AGI Tx >> agi_channel: SIP/8004-0000000b
<SIP/8004-0000000b>AGI Tx >> agi_language: br
<SIP/8004-0000000b>AGI Tx >> agi_type: SIP
<SIP/8004-0000000b>AGI Tx >> agi_uniqueid: 1515931467.15
<SIP/8004-0000000b>AGI Tx >> agi_version: certified/13.13-cert9
<SIP/8004-0000000b>AGI Tx >> agi_callerid: 8004
<SIP/8004-0000000b>AGI Tx >> agi_calleridname: 8004
<SIP/8004-0000000b>AGI Tx >> agi_callingpres: 0
<SIP/8004-0000000b>AGI Tx >> agi_callingani2: 0
<SIP/8004-0000000b>AGI Tx >> agi_callington: 0
<SIP/8004-0000000b>AGI Tx >> agi_callingtns: 0
<SIP/8004-0000000b>AGI Tx >> agi_dnid: 8002
<SIP/8004-0000000b>AGI Tx >> agi_rdnis: unknown
<SIP/8004-0000000b>AGI Tx >> agi_context: ivrtime
<SIP/8004-0000000b>AGI Tx >> agi_extension: s
<SIP/8004-0000000b>AGI Tx >> agi_priority: 4
<SIP/8004-0000000b>AGI Tx >> agi_enhanced: 0.0
<SIP/8004-0000000b>AGI Tx >> agi_accountcode:
<SIP/8004-0000000b>AGI Tx >> agi_threadid: 140167000688384
<SIP/8004-0000000b>AGI Tx >> agi_arg_1: Digite o seu numero de cliente assim eu posso lhe identificar
<SIP/8004-0000000b>AGI Tx >> agi_arg_2: pt-BR
<SIP/8004-0000000b>AGI Tx >>
<SIP/8004-0000000b>AGI Rx << CHANNEL STATUS
<SIP/8004-0000000b>AGI Tx >> 200 result=6
<SIP/8004-0000000b>AGI Rx << GET FULL VARIABLE ${CHANNEL(audionativeformat)}
<SIP/8004-0000000b>AGI Tx >> 200 result=1 ((alaw))
<SIP/8004-0000000b>AGI Rx << NOOP " -- googletts.agi: Text passed for synthesis: Digite o seu numero de cliente assim eu posso lhe identificar."
<SIP/8004-0000000b>AGI Tx >> 200 result=0
<SIP/8004-0000000b>AGI Rx << NOOP " -- googletts.agi: Language: pt-BR, Interrupt keys: , Sample rate: 8000"
<SIP/8004-0000000b>AGI Tx >> 200 result=0
<SIP/8004-0000000b>AGI Rx << NOOP " -- googletts.agi: Speed: 1, Caching: 1, Cache dir: /tmp"
<SIP/8004-0000000b>AGI Tx >> 200 result=0
<SIP/8004-0000000b>AGI Rx << NOOP " -- googletts.agi: URL passed: https://translate.google.com/translate_tts?ie=UTF-8&q=Digite%20o%20seu%20numero%20de%20cliente%20assim%20eu%20posso%20lhe%20identificar.&tl=pt-BR&total=1&idx=0&textlen=62&client=tw-ob&tk=222746.330494&prev=input"
<SIP/8004-0000000b>AGI Tx >> 200 result=0
<SIP/8004-0000000b>AGI Rx << NOOP " -- googletts.agi:  failed: -1"
<SIP/8004-0000000b>AGI Tx >> 200 result=0
    -- <SIP/8004-0000000b>AGI Script googletts.agi completed, returning 0

**Comment by fabiosangiorgi** [comment]
first
 yum install sox sox-devel sox-devel mpg123 perl-LWP-Protocol-https perl-Crypt-SSLeay perl-LWP-Protocol-https perl-Crypt-SSLeay perl-libwww-perl perl-LWP-Protocol-https perl-HTTP-Message perl-XML-Simple perl-Crypt-SSLeay perl-libwww-perl perl-XML-Simple perl-IO-Socket-SSL.noarch 


to search for the correct path for sox and mpg123
which soxwhich mpg123 
and edit my $sox     = "/usr/bin/sox";
my $mpg123  = "/usr/bin/mpg123"; 
in /var/lib/asterisk/agi-bin/googletts.agi

edit my $cachedir = "/tmpasterisk";in /var/lib/asterisk/agi-bin/googletts.agi
mkdir /tmpastersikchown asterisk:astersik /tmpastersik
chmod +x /tmpastersik
chown asterisk:astersik /var/lib/asterisk/agi-bin/googletts.agi




Dott. Fabio Sangiorgi
fabiosangiorgi@yahoo.it
tel. 3331467114
fax 09123860599 

    Il Domenica 14 Gennaio 2018 13:15, JSilva <notifications@github.com> ha scritto:
 

 Good Morning.I did another test, I disabled in the code line of "googletts.agi" where check the mpg123 and sox both are already installed.Commented line:
Abort if required programs not found.
fatal_log ("sox or mpg123 is missing. Aborting.") if (! $ sox || $ mpg123);
chomp ($ sox, $ mpg123);Follow the new error log, I notice that it generates the link with the message, but it does not start in linux, I validated the link, it works.I'm using CentOS7.I will send the log after commenting the line, as I mentioned above.Launched AGI Script /var/lib/asterisk/agi-bin/googletts.agi
<SIP/8004-0000000b>AGI Tx >> agi_request: googletts.agi
<SIP/8004-0000000b>AGI Tx >> agi_channel: SIP/8004-0000000b
<SIP/8004-0000000b>AGI Tx >> agi_language: br
<SIP/8004-0000000b>AGI Tx >> agi_type: SIP
<SIP/8004-0000000b>AGI Tx >> agi_uniqueid: 1515931467.15
<SIP/8004-0000000b>AGI Tx >> agi_version: certified/13.13-cert9
<SIP/8004-0000000b>AGI Tx >> agi_callerid: 8004
<SIP/8004-0000000b>AGI Tx >> agi_calleridname: 8004
<SIP/8004-0000000b>AGI Tx >> agi_callingpres: 0
<SIP/8004-0000000b>AGI Tx >> agi_callingani2: 0
<SIP/8004-0000000b>AGI Tx >> agi_callington: 0
<SIP/8004-0000000b>AGI Tx >> agi_callingtns: 0
<SIP/8004-0000000b>AGI Tx >> agi_dnid: 8002
<SIP/8004-0000000b>AGI Tx >> agi_rdnis: unknown
<SIP/8004-0000000b>AGI Tx >> agi_context: ivrtime
<SIP/8004-0000000b>AGI Tx >> agi_extension: s
<SIP/8004-0000000b>AGI Tx >> agi_priority: 4
<SIP/8004-0000000b>AGI Tx >> agi_enhanced: 0.0
<SIP/8004-0000000b>AGI Tx >> agi_accountcode:
<SIP/8004-0000000b>AGI Tx >> agi_threadid: 140167000688384
<SIP/8004-0000000b>AGI Tx >> agi_arg_1: Digite o seu numero de cliente assim eu posso lhe identificar
<SIP/8004-0000000b>AGI Tx >> agi_arg_2: pt-BR
<SIP/8004-0000000b>AGI Tx >>
<SIP/8004-0000000b>AGI Rx << CHANNEL STATUS
<SIP/8004-0000000b>AGI Tx >> 200 result=6
<SIP/8004-0000000b>AGI Rx << GET FULL VARIABLE ${CHANNEL(audionativeformat)}
<SIP/8004-0000000b>AGI Tx >> 200 result=1 ((alaw))
<SIP/8004-0000000b>AGI Rx << NOOP " -- googletts.agi: Text passed for synthesis: Digite o seu numero de cliente assim eu posso lhe identificar."
<SIP/8004-0000000b>AGI Tx >> 200 result=0
<SIP/8004-0000000b>AGI Rx << NOOP " -- googletts.agi: Language: pt-BR, Interrupt keys: , Sample rate: 8000"
<SIP/8004-0000000b>AGI Tx >> 200 result=0
<SIP/8004-0000000b>AGI Rx << NOOP " -- googletts.agi: Speed: 1, Caching: 1, Cache dir: /tmp"
<SIP/8004-0000000b>AGI Tx >> 200 result=0
<SIP/8004-0000000b>AGI Rx << NOOP " -- googletts.agi: URL passed: https://translate.google.com/translate_tts?ie=UTF-8&q=Digite%20o%20seu%20numero%20de%20cliente%20assim%20eu%20posso%20lhe%20identificar.&tl=pt-BR&total=1&idx=0&textlen=62&client=tw-ob&tk=222746.330494&prev=input"
<SIP/8004-0000000b>AGI Tx >> 200 result=0
<SIP/8004-0000000b>AGI Rx << NOOP " -- googletts.agi: failed: -1"
<SIP/8004-0000000b>AGI Tx >> 200 result=0
-- <SIP/8004-0000000b>AGI Script googletts.agi completed, returning 0—

**Comment by janduy** [comment]
@fabiosangiorgi 

Hello, I'm going to check the dependencies that I have passed, I believe that almost all I have installed, I followed the dependencies of the "readme" file of the googletts github that I downloaded. I'll check and put the result here.

thank you!

**Comment by janduy** [comment]
@fabiosangiorgi 

The only missing dependencies were these "XML" but it did not work. =(

Have been installed:
perl-XML-NamespaceSupport
perl-XML-Parser-2.41-10.el7.x86_64
perl-XML-SAX-Base-1.08-7.el7.noarch 
perl-XML-SAX-0.99-9.el7.noarch
perl-XML-Simple-2.20-5.el7.noarch

**Comment by fabiosangiorgi** [comment]
URL passed:

https://translate.google.com/translate_tts?ie=UTF-8&q=Digite%20o%20seu%20numero%20de%20cliente%20assim%20eu%20posso%20lhe%20identificar.&tl=pt-BR&total=1&idx=0&textlen=62&client=tw-ob&tk=222746.330494&prev=input

not work. In the test sent for the tts the **double quote is missing**. Test:

https://translate.google.com/translate_tts?ie=UTF-8&q=%22Digite%20o%20seu%20numero%20de%20cliente%20assim%20eu%20posso%20lhe%20identificar.%22&tl=pt-BR&total=1&idx=0&textlen=62&client=tw-ob&tk=222746.330494&prev=input


use in extensions_custom.conf

exten => _.,n,agi(googletts.agi,"${variable}",pt)

**Comment by janduy** [comment]
@fabiosangiorgi 

I understand, you want me to define the variable with the link and then I call it in my dialplan, correct?

I can validate yes, at the moment I'm on the cell phone, as soon as I'm home I'll test.

Regards,
Janduy Euclides.

**Comment by DorianMaliszewski** [comment]
To solve this on RHEL 7 / CentOS 7  verify dependencies.
- `yum install -y perl-LWP-Protocol-https perl mpg123 sox perl-libwww-perl`

:100:

**Comment by youchi99** [comment]
it works for me thank you

**Comment by aruto99** [comment]
Hi,
I have a problem with googletts.agi (Astereisk OpenWRT)
Its simple dialplan. CLI logs 
   -- Executing [1000@nasz-dialplan:1] Answer("PJSIP/1002-00000006", "") in new stack
    -- Executing [1000@nasz-dialplan:2] Wait("PJSIP/1002-00000006", "1") in new stack
    -- Executing [1000@nasz-dialplan:3] AGI("PJSIP/1002-00000006", "googletts.agi,"Witamy. Pierwszy test.",pl") in new stack
    -- Launched AGI Script /usr/share/asterisk/agi-bin/googletts.agi
[Mar  9 11:17:02] ERROR[2860][C-00000006]: pbx_functions.c:651 ast_func_read2: Function CHANNEL not registered
 -- googletts.agi: Text passed for synthesis: Witamy. Pierwszy test.
 -- googletts.agi: Language: pl, Interrupt keys: , Sample rate: 8000
 -- googletts.agi: Speed: 1, Caching: 1, Cache dir: /tmp
 -- googletts.agi: URL passed: https://translate.google.com/translate_tts?ie=UTF-8&q=Witamy.%20Pierwszy%20test.&tl=pl&total=1&idx=0&textlen=22&client=tw-ob&tk=870144.769515&prev=input
 -- googletts.agi: Failed to fetch file:
 -- googletts.agi: 501
 -- googletts.agi: Protocol scheme 'https' is not supported (LWP::Protocol::https not installed)
Died at /usr/share/asterisk/agi-bin/googletts.agi line 360, <STDIN> line 32.
 -- googletts.agi: Cleaning temp files.
    -- <PJSIP/1002-00000006>AGI Script googletts.agi completed, returning 0
    -- Executing [1000@nasz-dialplan:4] Hangup("PJSIP/1002-00000006", "") in new stack
  == Spawn extension (nasz-dialplan, 1000, 4) exited non-zero on 'PJSIP/1002-00000006'

as we can see there is no LWP::Protocol::https. 
I looking on the net how can i install this packet but i nowhere find it maybe some one can help me.
